# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: None
    userGroups: ["system:authenticated", "system:nodes", "system:masters"]
    nonResourceURLs:
      - "/api*"
      - "/healthz*"

  - level: Request